extra-deps: []
resolver: lts-7.11
nix:
  enable: false
  packages:
  - haskellPackages.gtk2hs-buildtools
  - haskellPackages.pango
  - haskellPackages.cairo
  - haskellPackages.glib
  - haskellPackages.gtk3
  - pkgconfig
  - glib
  - cairo
  - gtk3
  - zlib
flags: {}
extra-package-dbs: []
packages:
- '.'
